---
- name: "Install httpd in distribuition based in RedHat"
  yum:
    name: 
      - httpd
      - openssl
    state: latest
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - enableHttpd

- name: "CriaDirVhostRedHat"
  file:
    path: "/etc/httpd/vhost.d"
    state: directory
  when: (ansible_facts['os_family'] == "RedHat")

- name: "Create an virtual host with settings from the site - RedHat" 
  template:
    src: templates/site.conf
    dest: /etc/httpd/vhost.d/{{ log_prefix }}.conf
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - addInHostsFile
    - addInHttpdFile
    - RestartHttpd
    - InstallWordPress
    - SetPermissionWP-CentOS
